### PR TITLE
CLDR-17610 v46 BRS: update charts with final 46 data

### PR DESCRIPTION
**Pull request by srl295**
CLDR-17610

v46 BRS: update charts with final 46 data

### CODE REVIEW

**Comment by srl295** [comment]
maven build failure is a dependency problem, will fix but doesn't affect charts

**Comment by srl295** [comment]
merging to fix build issue

**Review by AEApple — APPROVED** [review]

**Comment by AEApple** [comment]
I went back and updated the PR description since it's easier to click through to the ticket which is why I had re-requested my review.

**Comment by srl295** [comment]
> I went back and updated the PR description since it's easier to click through to the ticket which is why I had re-requested my review.

sounds good.

it's also there on the commit

image

**Pull request merged**
