### PR TITLE
CLDR-14461 fix .zip to include DTD

### PR DESCRIPTION
**Pull request by srl295**
CLDR-14461 the .zip files  did not include DTDs

Note: PR is on maint/maint-39

### CODE REVIEW

**Review by macchiati — CHANGES_REQUESTED** [review]
It also needs to include .txt files, .tsv files and others. Is there a way to make this more robust?

**Comment by srl295** [comment]
> It also needs to include .txt files, .tsv files and others. Is there a way to make this more robust?

Hmm. This Is the core / common .zip file. It is always somewhat limited in what is inside. I didn't think .tsv and .txt files were in cldr-staging/production, are they?

**Comment by macchiati** [comment]
Yes, they are.

[image: Screen Shot 2021-04-08 at 16.07.24.png]

Mark

**Comment by srl295** [comment]
Had not seen this.

> more robust

Sure, it’s just paths, whatever path we want to include is fine. I was
using an outdated model of the core.zip

Can fix tomorrow/?

**Comment by macchiati** [comment]
Yes, tomorrow's fine.

**Comment by srl295** [comment]
@macchiati neither CLDR 38 nor 38.1 zip files  contained .tsv files .  38 did not contain any of properties.

**Comment by srl295** [comment]
Updated artifacts will be attached to the build in progress https://github.com/unicode-org/cldr-staging/runs/2307934627?check_suite_focus=true

**Comment by srl295** [comment]
@macchiati please look at the "core.zip" artifact attached to https://github.com/unicode-org/cldr-staging/actions/runs/733810244 - it will unpack to a cldr-common.zip and cldr-keyboards.zip

**Comment by macchiati** [comment]
I downloaded the core.zip file, unzipped recursively, and it matches the
production maint-39 branch locally (except for .DSStore files, which are an
artifact we don't want in the zips).

*So that is all ready to go!*

BTW, please update the BRS instructions to include this verification step.

Mark

**Review by macchiati — APPROVED** [review]

**Pull request merged**
