### PR TITLE
CLDR-15136 delete docs/charts/latest and docs/charts/3*

### PR DESCRIPTION
**Pull request by srl295**
smoketest running out of space

all of this is on `www.unicode.org/cldr/charts/*`

I've also made unpublished proposed changes to cldr.unicode.org

### CODE REVIEW

**Comment by btangmu** [comment]
github is claiming an infinite number of files changed! and saying,

 Sorry, this diff is taking too long to generate.

It may be too large to display on GitHub.

**Comment by srl295** [comment]
> github is claiming an infinite number of files changed! and saying,

😅 yeah, it took me forever to push!

Actually there are 5,956 files deleted. 

> Sorry, this diff is taking too long to generate.
> 
> It may be too large to display on GitHub.

**Comment by btangmu** [comment]
it actually has ∞ and a pop-up saying "infinity"!

**Comment by srl295** [comment]
@btangmu  If you do a `git fetch` on this repo, you might be able to do:

```shell
$ git diff origin/trim20230509~ --name-status
D	docs/charts/37/annotations/afro_asiatic.html
D	docs/charts/37/annotations/americas.html
D	docs/charts/37/annotations/artificial.html
D	docs/charts/37/annotations/austro_asiatic.html
D	docs/charts/37/annotations/austronesian.html
D	docs/charts/37/annotations/baltic.html
D	docs/charts/37/annotations/celtic.html
D	docs/charts/37/annotations/cjk.html
D	docs/charts/37/annotations/dravidian.html
D	docs/charts/37/annotations/germanic.html
… 6000 lines deleted …
$ git diff origin/trim20230509~ --name-status | grep -v '^D'
# no lines returned… 100% deletions
```

**Comment by btangmu** [comment]
in progress using gh locally... slow...

**Review by btangmu — APPROVED** [review]
I've confirmed that the changes are all deletions of files, all in docs/charts

**Pull request merged**
