### PR TITLE
CLDR-17227 v45 charts regen

### PR DESCRIPTION
**Pull request by srl295**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-17227
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by macchiati** [comment]
No ticket # in the description.

**Review by macchiati — COMMENTED** [review]
I'm confused; I had just rebuilt the charts, and expected to see very few changes, but I'm seeing almost every file change. 

- I have to use the magic dot to be able to see diffs; I see a number of files that appear not to differ (invisible characters??)

**Comment by macchiati** [comment]
That is, I had just rebuilt the charts yesterday, and wouldn't expect that many chart files to change.

**Comment by srl295** [comment]
What options did you use to build? Against what tag of CLDR staging ?

**Comment by srl295** [comment]
mine is against cldr-staging 4f46f9f0d53830e9ded53687f33eb128d81af798 and cldr main 8ec09883def28bafb42796dd4cfac06cc6746131

**Comment by macchiati** [comment]
Mine was against head of main, as of sometime yesterday (BTW, makes sense
to record the hash in the PR).

**Comment by macchiati** [comment]
I'll go ahead and approve, then rebuild on my side to see if I get
differences.

**Review by macchiati — APPROVED** [review]

**Comment by srl295** [comment]
We can get the hash automatically.

**Comment by macchiati** [comment]
When we generate the charts locally, how does the github hash for the cldr repository appear in the PR for cldr-staging or in the body of the charts?

**Pull request merged**
