### PR TITLE
CLDR-17539 CLDR 45 beta4 production data update

### PR DESCRIPTION
**Pull request by DraganBesevic**
##### Checklist

- [ ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-17539
- [ ] Updated PR title and link in previous line to include Issue number

Production data for CLDR 45 beta 4

### CODE REVIEW

**Review by macchiati — APPROVED** [review]

**Comment by srl295** [comment]
@DraganBesevic any issue w/ merging this? I can do so if you like?

**Comment by markusicu** [comment]
Some of us are eagerly waiting for the beta4 tag with the data that went into ICU 75...

**Comment by markusicu** [comment]
> > Some of us are eagerly waiting for the beta4 tag with the data that went into ICU 75...
> 
> Merged and tagged :)

Thanks!
Will there be a tag also in the main repo? https://github.com/unicode-org/cldr/tags

**Comment by DraganBesevic** [comment]
> > > Some of us are eagerly waiting for the beta4 tag with the data that went into ICU 75...
> > 
> > 
> > Merged and tagged :)
> 
> Thanks! Will there be a tag also in the main repo? https://github.com/unicode-org/cldr/tags

On the way

**Comment by DraganBesevic** [comment]
> > > Some of us are eagerly waiting for the beta4 tag with the data that went into ICU 75...
> > 
> > 
> > Merged and tagged :)
> 
> Thanks! Will there be a tag also in the main repo? https://github.com/unicode-org/cldr/tags

https://github.com/unicode-org/cldr/releases/tag/release-45-beta4

**Pull request merged**
