### PR TITLE
CLDR-17227 CLDR 45 finalcharts

### PR DESCRIPTION
**Pull request by srl295**
- Removes the 'beta' tag from charts! 

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-17227
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by srl295** [comment]
Something's wrong with the chart generation.  GenerateAllCharts returns an error status at the end but doesn't generate all charts.  So this may be incomplete.. investigating

**Comment by macchiati** [comment]
> GenerateAllCharts returns an error status at the end but doesn't generate all charts. So this may be incomplete.. investigating

Is this resolved? Do we know the problem?

**Comment by srl295** [comment]
> > GenerateAllCharts returns an error status at the end but doesn't generate all charts. So this may be incomplete.. investigating
> 
> Is this resolved? Do we know the problem?

I think it was perhaps due to Java 21. Re-ran with Java 17 and it passed.

**Review by macchiati — APPROVED** [review]

**Comment by macchiati** [comment]
Hmmm. That blew up the number of files compared to your earlier versions.

It looks like the version is being included in a comment, which bypasses
the include file mechanism. That appears to be 'bout everything in

   - by_type
   - summary

Could you file a ticket to fix that, with a pointer to this PR?

**Comment by srl295** [comment]
> Hmmm. That blew up the number of files compared to your earlier versions.


Filed https://unicode-org.atlassian.net/browse/CLDR-17552

**Comment by macchiati** [comment]
Thanks!

**Pull request merged**
