### PR TITLE
CLDR-14260 create production zips with "mvn package"

### PR DESCRIPTION
**Pull request by srl295**
CLDR-14260

### CODE REVIEW

**Comment by srl295** [comment]
on push, you'll be able to download core.zip and keyboards.zip directly from https://github.com/unicode-org/cldr-staging/actions

**Comment by srl295** [comment]
it works! 🎉  checkout https://github.com/unicode-org/cldr-staging/actions/runs/399467809 for example, you can download 'core.zip' and 'keyboards.zip' directly…

**Comment by srl295** [comment]
yes, README-keyboards.md and README-common.md can be updated… like to do those in future PRs. (FYI:   @xadxura @sven-oly  )

**Review by rickmcgowan — APPROVED** [review]
Not familiar with Maven per se, but all looks reasonable. Seems to include the right license/copyright files and such in the package.

**Comment by srl295** [comment]
Great. Whenever someone tags this repo, you can find the corresponding zips under the Actions tab.

**Pull request merged**
